[build]
builder = "NIXPACKS"

# Service w: Backend
[[services]]
name = "backend"
root = "backend"
buildCommand = "pip install --no-cache-dir -r requirements.txt"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

# Service 2: Frontend
[[services]]
name = "frontend"
root = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm start"
